groups:
  - desktop
  - work
recipes:
  mac_os_x:
    - osxdefaults::disable_auto-correct
    - osxdefaults::disable_natural_scrolling
    - osxdefaults::dock_automatically_hide_and_show_the_dock
attributes:
  homebrewalt:
    apps:
      - ack
      - ag
      - axel
      - macvim
      - rbenv
      - rbenv-aliases
      - rhash
      - ruby-build
      - wget
      - zsh
    cask_apps:
      - iterm2
