recipes:
  mac_os_x:
    - osxdefaults::set_computer_name
attributes:
  homebrewalt:
    apps:
      - heroku-toolbelt
      - terminal-notifier
      - unrar
      - youtube-dl
    cask_apps:
      - 1password
      - alfred
      - airfoil
      - arq
      - dropbox
      - firefox
      - google-chrome
      - google-chrome-canary
      - mplayerx
      - nvalt
      - spotify
      - vlc
  osxdefaults:
    computername: Wassail
