recipes:
  mac_os_x:
    # - apm::default
    - homebrew::install_formulas
    - homebrew::install_casks
    - homebrew::install_taps
    - dotfiles::atom
    - dotfiles::hammerspoon
    - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
    - osxdefaults::set_computer_name
    - osxdefaults::menu_hide
    - osxdefaults::reduce_transparency
attributes:
  homebrew:
    formulas:
      - dockutil
      - ffmpeg
      - gdm
      - go
      - heroku-toolbelt
      - imapfilter
      - influxdb
      - letsencrypt
      - lua
      - node
      - pstree
      - python
      - qemu
      - rsync
      - telegraf
      - terminal-notifier
      - unrar
      - youtube-dl
    casks:
      - 1password
      - alfred
      - airfoil
      - arq
      - atom
      - audacity
      - battle-net
      - busycal
      - cleanmymac
      - dash
      - dropbox
      - firefox
      - font-hack
      - font-inconsolata
      - fluid
      - flux
      - freemind
      - grammarly
      - goofy
      - google-chrome
      - google-chrome-canary
      - hammerspoon
      - imageoptim
      - karabiner
      - mplayerx
      - nvalt
      - packer
      - postico
      - qlcolorcode
      - qlmarkdown
      - qlstephen
      - track-o-bot
      - transmission
      - silverlight
      - slack
      - spotify091527
      - vagrant
      - vlc
    taps:
      - caskroom/fonts
      - h13ronim/otg
  apm:
    packages:
      - atom-beautify
      - atom-fuzzy-grep
      - file-icons
      - fonts
      - git-plus
      - language-haml
      - language-lua
      - linter
      - linter-csslint
      - linter-haml
      - linter-jsonlint
      - linter-lua
      - linter-php
      - linter-ruby
      - linter-scss-lint
      - pigments
      - project-manager
      - rails-open-rspec
      - react
      - sort-lines
      - tabularize
      - toggle-quotes
  osxdefaults:
    computername: Wassail
