recipes:
  mac_os_x:
    - osxdefaults::set_computer_name
    - apm::default
attributes:
  homebrewalt:
    apps:
      - heroku-toolbelt
      - terminal-notifier
      - unrar
      - youtube-dl
    cask_apps:
      - 1password
      - alfred
      - airfoil
      - arq
      - atom
      - dropbox
      - firefox
      - google-chrome
      - google-chrome-canary
      - mplayerx
      - nvalt
      - spotify
      - vlc
  osxdefaults:
    computername: Wassail
  apm:
    packages:
      - atom-beautify
      - atom-fuzzy-grep
      - file-icons
      - fonts
      - git-plus
      - language-haml
      - language-lua
      - linter
      - linter-csslint
      - linter-haml
      - linter-jsonlint
      - linter-lua
      - linter-php
      - linter-ruby
      - linter-scss-lint
      - pigments
      - project-manager
      - rails-open-rspec
      - react
      - sort-lines
      - tabularize
      - toggle-quotes
